### ISSUE TITLE
/bin/bash^M: bad interpreter

### ISSUE THREAD

**Issue by jbondhus** [Ahtenus/minecraft-init#102]
When I try starting the server with the init script, I get this error:

```
-bash: /home/minecraft/minecraft-init/minecraft: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by Rovanion** [comment]
Seems like you have some sort of encoding issue going on. What is the output of:

``` bash
file minecraft
```

It should read: minecraft: Bourne-Again shell script, ASCII text executable

If you edit the file with your favourit editor emacs you'll probably see these characters sprinkled all over the place. They are the Windows newline characters. The gnu utility fromdos will probably fix it:

``` bash
fromdos minecraft
```

**Comment by jbondhus** [comment]
Ok, the dos2unix command fixed it. Now I'm getting [this](http://pastebin.com/U9QVz3ze) error. When I run it with the bash -x command to get verbose information, I get [this](http://pastebin.com/6mmaU127) (until I cancel it with control + c).

**Comment by Rovanion** [comment]
Yeah, try and pull the script from the repo again. I think at some point someone submitted a new scheme to find wether or not the server is running and it ended up breaking for quite some.

**Comment by jbondhus** [comment]
Ok, I'll try re-pulling it. I believe this to be the most recent version, but it doesn't hurt to double-check, I could be wrong.

UPDATE: Now it has the encoding issue again. I fixed it, but since nothing was changed in the text (even though the file is different), it won't sync the changes. If you want to take a look at the new scheme issue you can download my copy or change the encoding back to UNIX again on your copy. I'm using the very latest copy by the way.

**Comment by Rovanion** [comment]
Your encoding issues are due to you using git in Windows. ^M is the standard Windows newline character.

I'm not sure what you're saying in the rest of the message.

The issues you seem to having after fixing the encoding issues seem to be the same as in this bug report: https://github.com/Ahtenus/minecraft-init/issues/101

This issue should be closed now as it's specific issue has been solved.

**Comment by jbondhus** [comment]
Ok, but there is still the other issue, with the new scheme. That's in the lastest version as well.

**Comment by Rovanion** [comment]
Yes. The issue referenced is still open is it not?

**Comment by jbondhus** [comment]
Yeah, it's been open for a week now though with no solutions.

**Comment by Rovanion** [comment]
A temporary solution would be to just revert to an earlier commit. If you don't want to solve the issue I would probably go down that route. Look at the man-page for git-reset for instructions on how to do that. Should be something like git reset --hard <commit hash>, but I'm unsure.

**Comment by jbondhus** [comment]
I think I'm just gonna see if it's possible to revert to the previous way of starting the server. This solution one seems error-ridden, and I never had any problems with the old one. The new method almost seems like a backwards step.

**Comment by Rovanion** [comment]
Technically the pid-file solution is preferred and is the proper way to keep track on wether or not a service is running. But obviously the implementation was bad in this case.

**Comment by jbondhus** [comment]
Well in the meantime, I think it would be best to rollback the entire script to the old method, because it's better than fixing something that isn't broken and breaking it in the process. When we get a correct way of doing it and it tests as working, then we can switch to the PID method. I don't have anything against the PID method, what I'm against is implementing new features that break the overall product.

**Comment by Rovanion** [comment]
Of course. Either the code was merged without testing on Ahtenus end or the
bug only occurs on specific setups.

But you have to remember that this is not a large scale project. The reason
this has been fixed for a week is either that noone involved has the
knowledge to fix it or the time to fix it. Either way the main branch
should be reverted to the old grep method. But even that only happens when
@Ahtenus finds time to do it.

2012/11/9 Jonathan Bondhus notifications@github.com

**Comment by Rovanion** [comment]
Of course it also has to be fixed by someone who has the issue or those
with the issue have to provide enough information for the issue to be fixed.

2012/11/9 Pascal König notifications@github.com

**Comment by jbondhus** [comment]
I would be more than happy to give you the information. I am running Debian 6 (Squeeze) on Linux kernel version 2.6.32-5-686 on an i686 based processor. My file permissions for the minecraft directory and minecraft-init directory and all files within have permissions set either as drwxr-xr-x or drwxrwxrwx, with the owner being the user minecraft. I have 2 GB of ram, and a configuration file which you can view [here](http://pastebin.com/hFnhacmd). As I said earlier, "Now I'm getting this error. When I run it with the bash -x command to get verbose information, I get this (until I cancel it with control + c)." I did some testing, such as moving the old functions (the older versions of mc_start and is_running) into the new script, and it managed to launch, however, it had some bugs because I simply copied and pasted the functions in and didn't adjust any of the rest of the script to them.

**Comment by sockenklaus** [comment]
Do you launch the server with the user "mincraft" but start the script with the user "root"? There is a known issue, with screen and Debian 6, that causes some trouble, when you log on to your linux server with the user "root" (so that the shell, you start the script from, belongs to root) and start the script, that runs the minecraft-server with any other user.

**Comment by jbondhus** [comment]
No, I launch both with the user minecraft. It only restarts with user root upon restart (it's an init script), and since the update of the script which broke it, I've launched it entirely with the user minecraft (except for one restart, which still didn't fix it). It always worked in the past even launching it as root for me.
